apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: raveendranpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: raveendranpipelinesjavascriptdocker 
    spec:
      containers:
        - name: raveendranpipelinesjavascriptdocker 
          image: raveecontainerregistry.azurecr.io/raveendranpipelinesjavascriptdocker
          ports:
          - containerPort: 8080